spring.application.name=authorization-service

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${DB_IP:localhost}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:vutzu}
database.password = ${DB_PASSWORD:root}
database.name = ${DB_DBNAME:credential_db}

spring.sql.init.platform=postgres
spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

# Hibernate ddl auto
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

###############################################
### SERVER CONFIGURATION ###
###############################################
server.port=${PORT:8081}

###############################################
### JWT CONFIGURATION ###
###############################################
jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong}
jwt.expiration=${JWT_EXPIRATION:86400000}

###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.com.example=info

